### ISSUE TITLE
Where is the caffe.proto file ? 

### ISSUE THREAD

**Issue by andrewsx** [gustavla/autocolorize#16]
Hello,

In the README, I'm trying to find the proto folder containing this file but it's not there?

Thanks!

**Comment by gustavla** [comment]
This refers to a file in the Caffe repository and not this repository, since you'll need to compile these into Caffe.

https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto

I can't guarantee that this still works with the latest version though, since this was written a few years ago.
